container:
  image: cirrusci/flutter:stable
test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test test/unit_test.dart

widget_test_task:
  test_script: flutter test test/widget_test.dart

container:
  image: cirrusci/android-sdk:18
  cpu: 4
  memory: 10G

  check_android_task:
    create_device_script: >
      echo no | avdmanager create avd --force \
          -n test \
          -k "system-images;android-18;default;armeabi-v7a"
    start_emulator_background_script: >
      $ANDROID_HOME/emulator/emulator \
          -avd test \
          -no-audio \
          -no-window
    wait_for_emulator_script:
      - adb wait-for-device
      - adb shell input keyevent 82
    test_script: flutter drive --target=test_driver/app.dart