container:
  image: cirrusci/flutter:stable
test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test test/unit_test.dart

widget_test_task:
  test_script: flutter test test/widget_test.dart

android_test_task:
  start_emulator_background_script: emulator -avd test -no-audio -no-window
  wait_for_emulator_to_boot_script: adb wait-for-device
  test_script: flutter drive --target=test_driver/app.dart