container:
  image: cirrusci/flutter:stable
test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test test/unit_test.dart

widget_test_task:
  test_script: flutter test test/widget_test.dart

# android_test_task:
#   script: fastlane test